### ISSUE TITLE
How to configure the config-test.yaml with several entries?

### ISSUE THREAD

**Issue by andy-kwo-any** [mcorbin/cabourotte#10]
Hi,

I have been able to configure the `config-test.yaml` file with one entry, `korben.info`. Things are working good.

However, if I want to add several websites, how should I do that, please?

Cheers.

**Comment by mcorbin** [comment]
Hello,

The config takes a list of healthchecks, you can just add more items into it ;)

**Comment by andy-kwo-any** [comment]
Hi @mcorbin ,

I did this :

```
http-checks:
    # The healthcheck name
    #Garder
  - name: "Dallas check"
    description: "http healthcheck example"
    valid-status:
      - 200
      - 201
    target: "korben.info"
    port: 443
    body-regexp:
      - "tutos"    
    protocol: "https"
  - name: "SO check"
    description: "http healthcheck example"
    valid-status:
      - 200
      - 201
    target: "stackoverflow.com"
    port: 443
    body-regexp:
      - "Top Questions"    
    protocol: "https"    
    # The HTTP path of the healthcheck
    path: "/"
    # The healthcheck timeout
    timeout: 5s
    # The healthcheck interval
    interval: 10s
    # Follow redirect (optional, default false)
    redirect: true
    # Extra headers to add to the request (optional)
    headers:
      foo: "bar"
    # Body to pass to the request (optional)
    body: "my request body"
    # A list of regular expression. The response body should match them (optional)
    # permet de faire une recherche sur un mot du site
```

Issue is it is giving me the following errors

`2021/03/01 17:06:28 Fail to read the yaml config file: Invalid healthcheck configuration: The healthcheck timeout is missing`

Ty.
