### ISSUE TITLE
running correctly and then ...

### ISSUE THREAD

**Issue by andy-kwo-any** [mcorbin/cabourotte#6]
Hi,

When I'm running `Cabourotte` with the config below, I have the following error

`"cause":"HTTP request failed: Get \"https://mcorbin.fr:443/\": dial tcp 10.1.1.2:0->194.182.162.185:443: bind: cannot assign requested address",
`
This is the config file

```
# the http section is used to configure the Cabourotte HTTP server
http:
  # The HTTP server host
  host: "127.0.0.1"
  # The HTTP server port
  port: 9013
  # A cacert for mTLS (optional)
  #cacert: "/tmp/cacert.pem"
  # A cert for mTLS (optional)
  #cert: "/tmp/cert.pem"
  # A key for mTLS (optional)
  #key: "/tmp/foo.key"
# The dns-checks section can be used to configure DNS healthchecks
http-checks:
    # The healthcheck name
  - name: "mcorbin-http-check"
    # The healthcheck description
    description: "http healthcheck example"
    # The list of HTTP status codes to consider the healthcheck successful
    valid-status:
      - 200
      - 201
    # The healthcheck target. It can be an IP (v4 or v6) or a domain
    target: "mcorbin.fr"
    # The target port
    port: 443
    # The protocol (http or https)
    protocol: "https"
    # The HTTP path of the healthcheck
    path: "/"
    # The healthcheck timeout
    timeout: 5s
    # The healthcheck interval
    interval: 10s
    # Follow redirect (optional, default false)
    redirect: true
    # Extra headers to add to the request (optional)
    headers:
      foo: "bar"
    # Body to pass to the request (optional)
    body: "my request body"
    # A list of regular expression. The response body should match them (optional)
    body-regexp:
      - "foo!"
    # A cacert for mTLS (optional)
    #cacert: "/tmp/cacert.pem"
    # A cert for mTLS (optional)
    #cert: "/tmp/cert.pem"
    # A key for mTLS (optional)
    #key: "/tmp/foo.key"
    # Enable or disable insecure TLS connections (default to false)
    insecure: false
    # The source IP which will be used for healthchecks (optional)
    source-ip: "10.1.1.2"
    # Labels for this healthcheck. It will be used in logging and in
    # exporters (optional)
    labels:
      environment: prod
# The tcp-checks section can be used to configure HTTP healthchecks
```

Is there any hints on the reason?

Cheers
